# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e1bd072a52260b8d1448505b8342de23dc1d163f17c5f47c8fcde088d4373db6ff9969ead630307d98879fa137f4ebd5f34fb5a137b0016a09527c330301c72

test:
  secret_key_base: 4156608d68cd6522707813bac4a6e95b2e3e603b5bea26fca6c34dabcdd6486032308a724cf672d7aa6a1e39c7fc5918a999b7947788e8a203af6a4f7cdf457f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
